services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: docmost_dev_pass
      POSTGRES_DB: docmost
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
